### ISSUE TITLE
Reviews on tutorial 

### ISSUE THREAD

**Issue by belldandyxtq** [chenghuzi/doc-optuna-chinese#3]
https://github.com/chenghuzi/doc-optuna-chinese/blob/2004a3a7b56f7c5d29d1fecc689f387cbfced84a/source/locale/zh/LC_MESSAGES/tutorial/first.po#L85
The format is broken https://chinese-doc-optuna.onrender.com/tutorial/first.html#quadratic-function-example

**Comment by belldandyxtq** [comment]
https://github.com/chenghuzi/doc-optuna-chinese/blob/2004a3a7b56f7c5d29d1fecc689f387cbfced84a/source/locale/zh/LC_MESSAGES/tutorial/configurations.po#L78
This line is not shown in the webpage, maybe you want a "\\" at the end of the line

https://chinese-doc-optuna.onrender.com/tutorial/configurations.html#arguments-for-study-optimize

**Comment by belldandyxtq** [comment]
https://github.com/chenghuzi/doc-optuna-chinese/blob/2004a3a7b56f7c5d29d1fecc689f387cbfced84a/source/locale/zh/LC_MESSAGES/tutorial/rdb.po#L32
I feel the `多节点优化` is kinda confusing, it can mean optimizing the multi-node runs.
Using `分布式优化` is better and consistent

**Comment by belldandyxtq** [comment]
https://github.com/chenghuzi/doc-optuna-chinese/blob/2004a3a7b56f7c5d29d1fecc689f387cbfced84a/source/locale/zh/LC_MESSAGES/tutorial/distributed.po#L28
How about `Optuna的分布式优化不需要复杂的设置`

**Comment by belldandyxtq** [comment]
https://github.com/chenghuzi/doc-optuna-chinese/blob/2004a3a7b56f7c5d29d1fecc689f387cbfced84a/source/locale/zh/LC_MESSAGES/tutorial/distributed.po#L34

typo: `的话`

**Comment by belldandyxtq** [comment]
https://github.com/chenghuzi/doc-optuna-chinese/blob/2004a3a7b56f7c5d29d1fecc689f387cbfced84a/source/locale/zh/LC_MESSAGES/tutorial/cli.po#L46

`删除所给的study`

**Comment by belldandyxtq** [comment]
https://github.com/chenghuzi/doc-optuna-chinese/blob/2004a3a7b56f7c5d29d1fecc689f387cbfced84a/source/locale/zh/LC_MESSAGES/tutorial/attributes.po#L69
This line is not shown, maybe a "\\"

https://chinese-doc-optuna.onrender.com/tutorial/attributes.html#adding-user-attributes-to-trials

**Comment by belldandyxtq** [comment]
https://github.com/chenghuzi/doc-optuna-chinese/blob/2004a3a7b56f7c5d29d1fecc689f387cbfced84a/source/locale/zh/LC_MESSAGES/tutorial/sampler.po#L42
`流水线`

**Comment by belldandyxtq** [comment]
https://github.com/chenghuzi/doc-optuna-chinese/blob/2004a3a7b56f7c5d29d1fecc689f387cbfced84a/source/locale/zh/LC_MESSAGES/tutorial/sampler.po#L80
How about `你所定义的新 sampler需要继承 BaseSampler。`

**Comment by belldandyxtq** [comment]
https://github.com/chenghuzi/doc-optuna-chinese/blob/2004a3a7b56f7c5d29d1fecc689f387cbfced84a/source/locale/zh/LC_MESSAGES/tutorial/sampler.po#L134
Format is broken, missing "\\"?
https://chinese-doc-optuna.onrender.com/tutorial/sampler.html#an-example-implementing-simulatedannealingsampler

**Comment by belldandyxtq** [comment]
https://github.com/chenghuzi/doc-optuna-chinese/blob/2004a3a7b56f7c5d29d1fecc689f387cbfced84a/source/locale/zh/LC_MESSAGES/tutorial/cli.po#L62
`更新数据库scheme`

**Comment by chenghuzi** [comment]
Resolved in [5d6907cc540d5e99408af3b75337d4d09def1aca](https://github.com/chenghuzi/doc-optuna-chinese/commit/5d6907cc540d5e99408af3b75337d4d09def1aca).
